#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram>
# Description: Auto compile
#

#
# Fork and compile the latest version yourself using Github Actions
#   1.Into the repository of your own fork
#   2.Into the repository [Settings]
#   3.[Code and automation - Actions] ↓ [General] → [Workflow permissions] ↓  Check the [Read and write permissions] and [Save]
#   4.Let's take [Actions]
#

name: TEST Build OP Firmware
on:
  repository_dispatch:
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: sudo apt-get update && sudo apt-get install -y \
        build-essential \
        gcc \
        g++ \
        wget \
        tar \
        zlib1g-dev \
        libncurses5-dev \
        libssl-dev \
        gawk \
        subversion \
        python3 \
        python3-pip \
        git \
        unzip

    - name: Download OpenWrt SDK
      env:
          url_sdk: https://downloads.openwrt.org/releases/18.06.9/targets/x86/generic/openwrt-sdk-18.06.9-x86-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
      run: |
        wget ${{ env.url_sdk }}
          file_name=$(echo ${{env.url_sdk}} | awk -F/ '{print $NF}')
          mkdir sdk && tar -xJf $file_name -C ./sdk --strip-components=1

    - name: Configure OpenWrt
      run: |
        cd sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make menuconfig  # This step might require manual interaction to select options
    
    - name: Build firmware
      run: |
        cd sdk
        make -j1 V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: |
          sdk/bin/targets

