#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram>
# Description: Auto compile
#

#
# Fork and compile the latest version yourself using Github Actions
#   1.Into the repository of your own fork
#   2.Into the repository [Settings]
#   3.[Code and automation - Actions] ↓ [General] → [Workflow permissions] ↓  Check the [Read and write permissions] and [Save]
#   4.Let's take [Actions]
#

name: " test "
on:
  repository_dispatch:
  workflow_dispatch:
  

env:
  TZ: Asia/Shanghai
  ARCH: 8632
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-18.06

jobs:
  job_build_firmware:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main






    - name: Configure feeds.conf
      run: |
        #cd openwrt
        cat > feeds.conf  << EOF 
        src-git base https://github.com/openwrt/openwrt.git;openwrt-18.06
        src-git-full packages https://github.com/openwrt/packages.git;openwrt-18.06
        src-git-full luci https://git.openwrt.org/project/luci.git;openwrt-18.06
        src-git-full routing https://git.openwrt.org/feed/routing.git;openwrt-18.06   
        git clone https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter
        EOF
        git clone https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter
        git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/lean/luci-theme-argon
        #./scripts/feeds update -a        
        #./scripts/feeds install 

    - name: Configure .config file
      run: |
        #cd openwrt
        cat <<EOF > .config
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_generic=y
        CONFIG_TARGET_x86_generic_Generic=y
        CONFIG_TARGET_KERNEL_PARTSIZE=32
        CONFIG_TARGET_ROOTFS_PARTSIZE=500
        CONFIG_PACKAGE_luci-app-argon-config=y
        CONFIG_PACKAGE_luci-theme-argon=y
        CONFIG_PACKAGE_luci-theme-argon=y
        EOF       
        make defconfig

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt-x86-32
        path: openwrt/.config


    - name: Clone source code
      run: |
        df -h $PWD
        git clone  -b $REPO_BRANCH $REPO_URL openwrt
